# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='picture',
        ),
    ]
