# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 15:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0002_remove_picture_picture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='picture',
            old_name='location',
            new_name='geom',
        ),
    ]
