# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 17:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geoapp', '0003_auto_20171211_1543'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Picture',
        ),
    ]
